import { AuditReport, Severity } from '../types.js';

/**
 * Generate a standalone Markdown report suitable for sharing,
 * PRs, blog posts, or marketing materials.
 */
export function formatMarkdownReport(report: AuditReport): string {
  const lines: string[] = [];

  const grade = scoreGrade(report.score);
  const bar = renderBar(report.score);
  const repoName = report.repoPath.split('/').pop() || report.repoPath;

  lines.push(`# isolint Report: ${repoName}`);
  lines.push('');
  lines.push(`> Generated by [isolint](https://github.com/mabthew/isolint) — scans repos for hardcoded values that break parallel development workflows.`);
  lines.push('');

  // Score card
  lines.push('## Readiness Score');
  lines.push('');
  lines.push('```');
  lines.push(`${bar}  ${report.score}/100 (${grade})`);
  lines.push('```');
  lines.push('');

  // Stats table
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Files scanned | ${report.filesScanned.toLocaleString()} |`);
  lines.push(`| Scan time | ${formatDuration(report.duration)} |`);
  lines.push(`| Ecosystems detected | ${report.repoProfile.ecosystems.join(', ')} |`);
  lines.push(`| Total findings | ${report.findingsCount} |`);

  const critCount = report.findings.filter(f => f.severity === 'critical').length;
  const highCount = report.findings.filter(f => f.severity === 'high').length;
  const medCount = report.findings.filter(f => f.severity === 'medium').length;

  lines.push(`| Critical | ${critCount} |`);
  lines.push(`| High | ${highCount} |`);
  lines.push(`| Medium | ${medCount} |`);
  lines.push('');

  if (report.findings.length === 0) {
    lines.push('**No worktree-incompatible patterns found.** This repo is ready for parallel development.');
    lines.push('');
    return lines.join('\n');
  }

  // Category breakdown
  lines.push('## Findings by Category');
  lines.push('');
  lines.push('| Category | Count | Severity Breakdown |');
  lines.push('|----------|-------|--------------------|');
  for (const s of report.summary) {
    const parts: string[] = [];
    for (const [sev, count] of Object.entries(s.bySeverity)) {
      parts.push(`${count} ${sev}`);
    }
    lines.push(`| ${formatCategory(s.category)} | ${s.count} | ${parts.join(', ')} |`);
  }
  lines.push('');

  // Top issues (critical + high only)
  const topIssues = report.findings.filter(f => f.severity === 'critical' || f.severity === 'high');
  if (topIssues.length > 0) {
    lines.push('## Top Issues');
    lines.push('');

    // Group by file
    const byFile = new Map<string, typeof topIssues>();
    for (const f of topIssues) {
      const arr = byFile.get(f.filePath) || [];
      arr.push(f);
      byFile.set(f.filePath, arr);
    }

    for (const [filePath, findings] of byFile) {
      lines.push(`### \`${filePath}\``);
      lines.push('');
      for (const f of findings.slice(0, 5)) { // max 5 per file
        const icon = f.severity === 'critical' ? '🔴' : '🟡';
        lines.push(`- ${icon} **${f.severity.toUpperCase()}** Line ${f.line}: ${f.message}`);
      }
      if (findings.length > 5) {
        lines.push(`- ... and ${findings.length - 5} more`);
      }
      lines.push('');
    }
  }

  // What these issues mean
  lines.push('## What This Means');
  lines.push('');

  if (critCount > 0) {
    lines.push(`This repo has **${critCount} critical issues** that **will** cause failures when running parallel worktrees, CI matrix builds, or autonomous AI agent workflows. These include:`);
    lines.push('');
    const cats = report.summary.filter(s => s.bySeverity.critical);
    for (const s of cats) {
      lines.push(`- **${formatCategory(s.category)}**: ${explainCategory(s.category)}`);
    }
    lines.push('');
  }

  if (report.score >= 90) {
    lines.push('This repo is in good shape for parallel development with minor issues to address.');
  } else if (report.score >= 70) {
    lines.push('This repo needs some work before it can safely support parallel worktree workflows.');
  } else if (report.score >= 50) {
    lines.push('This repo has significant hardcoded values that will cause conflicts in parallel environments.');
  } else {
    lines.push('This repo is **not ready** for parallel development. Multiple hardcoded values will cause port conflicts, database collisions, and build failures across worktrees.');
  }
  lines.push('');

  // Footer
  lines.push('---');
  lines.push(`*Scanned ${report.filesScanned.toLocaleString()} files in ${formatDuration(report.duration)} on ${new Date(report.timestamp).toLocaleDateString()}*`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate a multi-repo comparison report.
 */
export function formatComparisonReport(reports: Array<{ name: string; report: AuditReport }>): string {
  const lines: string[] = [];

  lines.push('# Isolation Readiness: Open Source Benchmark');
  lines.push('');
  lines.push('> How ready are popular open-source projects for parallel development?');
  lines.push('> Scanned by [isolint](https://github.com/mabthew/isolint).');
  lines.push('');

  // Leaderboard
  const sorted = [...reports].sort((a, b) => b.report.score - a.report.score);

  lines.push('## Leaderboard');
  lines.push('');
  lines.push('| # | Project | Score | Grade | Files | Critical | High | Top Issue |');
  lines.push('|---|---------|-------|-------|-------|----------|------|-----------|');

  for (let i = 0; i < sorted.length; i++) {
    const { name, report } = sorted[i];
    const grade = scoreGrade(report.score);
    const crit = report.findings.filter(f => f.severity === 'critical').length;
    const high = report.findings.filter(f => f.severity === 'high').length;
    const topCat = report.summary[0]?.category ? formatCategory(report.summary[0].category) : '—';
    lines.push(`| ${i + 1} | **${name}** | ${report.score}/100 | ${grade} | ${report.filesScanned.toLocaleString()} | ${crit} | ${high} | ${topCat} |`);
  }
  lines.push('');

  // Visual scores
  lines.push('## Score Distribution');
  lines.push('');
  lines.push('```');
  for (const { name, report } of sorted) {
    const bar = renderBar(report.score);
    const pad = name.padEnd(14);
    lines.push(`${pad} ${bar} ${report.score}`);
  }
  lines.push('```');
  lines.push('');

  // Category heatmap
  lines.push('## Issue Categories Across Projects');
  lines.push('');
  const allCats = new Set<string>();
  for (const { report } of reports) {
    for (const s of report.summary) allCats.add(s.category);
  }
  const catList = Array.from(allCats);

  const header = '| Project | ' + catList.map(formatCategory).join(' | ') + ' |';
  const sep = '|---------|' + catList.map(() => '---').join('|') + '|';
  lines.push(header);
  lines.push(sep);

  for (const { name, report } of sorted) {
    const cells = catList.map(cat => {
      const s = report.summary.find(x => x.category === cat);
      return s ? String(s.count) : '—';
    });
    lines.push(`| **${name}** | ${cells.join(' | ')} |`);
  }
  lines.push('');

  // Key insights
  lines.push('## Key Insights');
  lines.push('');

  const avgScore = Math.round(reports.reduce((sum, r) => sum + r.report.score, 0) / reports.length);
  const totalFindings = reports.reduce((sum, r) => sum + r.report.findingsCount, 0);
  const totalFiles = reports.reduce((sum, r) => sum + r.report.filesScanned, 0);
  const totalCritical = reports.reduce((sum, r) => sum + r.report.findings.filter(f => f.severity === 'critical').length, 0);

  lines.push(`- **Average readiness score**: ${avgScore}/100 across ${reports.length} projects`);
  lines.push(`- **Total files scanned**: ${totalFiles.toLocaleString()}`);
  lines.push(`- **Total findings**: ${totalFindings} (${totalCritical} critical)`);

  // Most common category
  const catCounts: Record<string, number> = {};
  for (const { report } of reports) {
    for (const s of report.summary) {
      catCounts[s.category] = (catCounts[s.category] || 0) + s.count;
    }
  }
  const topCat = Object.entries(catCounts).sort((a, b) => b[1] - a[1])[0];
  if (topCat) {
    lines.push(`- **Most common issue**: ${formatCategory(topCat[0])} (${topCat[1]} findings across all projects)`);
  }

  const passing = reports.filter(r => r.report.score >= 80).length;
  lines.push(`- **${passing}/${reports.length}** projects score 80+ (ready for parallel worktrees with minor fixes)`);
  lines.push('');

  // What is this
  lines.push('## What is Parallel Dev Readiness?');
  lines.push('');
  lines.push('Modern development increasingly relies on parallel workflows — git worktrees for feature branches, CI matrix builds, and autonomous AI coding agents running simultaneously. Hardcoded ports, absolute paths, fixed Docker container names, and shared database connections cause these parallel environments to conflict.');
  lines.push('');
  lines.push('`isolint` scans for these patterns and scores repos on a 0-100 scale. A score of 100 means the repo is fully parameterized and safe for parallel development.');
  lines.push('');

  // Footer
  lines.push('---');
  lines.push(`*Generated by isolint on ${new Date().toLocaleDateString()}*`);
  lines.push('');

  return lines.join('\n');
}

// --- Helpers ---

function scoreGrade(score: number): string {
  if (score >= 95) return 'A+';
  if (score >= 90) return 'A';
  if (score >= 80) return 'B';
  if (score >= 70) return 'C';
  if (score >= 60) return 'D';
  return 'F';
}

function renderBar(score: number): string {
  const filled = Math.round(score / 5);
  const empty = 20 - filled;
  return '█'.repeat(filled) + '░'.repeat(empty);
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function formatCategory(cat: string): string {
  return cat.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

function explainCategory(cat: string): string {
  const explanations: Record<string, string> = {
    'hardcoded-port': 'Fixed port numbers that will cause "address already in use" errors',
    'absolute-path': 'Machine-specific paths that break on other machines or worktrees',
    'docker-conflict': 'Docker container/network names that collide across parallel runs',
    'database-string': 'Database connection strings with hardcoded names that cause data corruption',
    'build-directory': 'Shared build output directories that cause stale or corrupt builds',
    'shared-cache': 'Cache directories that corrupt when accessed by parallel processes',
    'pid-socket': 'PID and socket files that prevent multiple server instances',
    'temp-directory': 'Temp directories with fixed names that collide',
    'log-file-path': 'Log files that get overwritten by parallel processes',
  };
  return explanations[cat] || cat;
}
